from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path
from tkinter import messagebox


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
STATIC_ASSET_DIR = ROOT / "production" / "static"
BROADCAST_PROCESS = None
RGC_DISCORD_URL = "https://discord.gg/Axwwa8CUqt"
RGC_WEBSITE_URL = "https://www.realisticgamingcrew.com"

DARK_BG = "#071018"
PANEL_BG = "#101a24"
FIELD_BG = "#172331"
TEXT_FG = "#f4f7fb"
MUTED_FG = "#9fb0c2"
ACCENT = "#8b1e2d"
ACCENT_HOVER = "#a72a3a"
GREEN = "#158a4d"
STOP_RED = "#b73535"

LAUNCHER_FIELDS = [
    ("USE_OPENAI", "true"),
    ("OPENAI_API_KEY", ""),
    ("OPENAI_MODEL", "gpt-5.5"),
    ("USE_ELEVENLABS", "true"),
    ("ELEVENLABS_API_KEY", ""),
    ("LEAD_VOICE_ID", ""),
    ("COLOR_VOICE_ID", ""),
    ("PIT_VOICE_ID", ""),
    ("OVERLAY_EVENT_TITLE", "RGC AI Broadcast"),
    ("OVERLAY_RACE_SPONSOR", ""),
    ("OVERLAY_SERIES_NAME", ""),
    (
        "OVERLAY_BRAND_GRAPHICS",
        "/assets/rgc_motorsports.png,/assets/autism_awareness.png,/assets/keep_it_real.webp",
    ),
    ("USE_SPONSOR_READS", "true"),
    ("SPONSOR_READ_NAME", ""),
    ("SPONSOR_READ_CAUSE", ""),
    ("USE_NATIONAL_ANTHEM", "false"),
    ("NATIONAL_ANTHEM_AUDIO", ""),
    ("NATIONAL_ANTHEM_DURATION_SECONDS", "90"),
    ("PRACTICE_MUSIC_PLAYLIST", ""),
    ("CAUTION_REPLAY_AUDIO", ""),
    ("USE_LEAGUE_DRIVER_NOTES", "false"),
    ("LEAGUE_DRIVERS_CSV", "league/drivers.csv"),
    ("LEAGUE_STATS_CSV", "league/stats.csv"),
]


def load_env_file(path=ENV_PATH):
    values = {}
    path = Path(path)
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def save_env_file(values, path=ENV_PATH):
    lines = [
        "# Generated by RGC AI Broadcast Studio launcher.",
        "# You can still edit this file manually if needed.",
        "",
    ]
    for key, default in LAUNCHER_FIELDS:
        lines.append(f"{key}={values.get(key, default)}")
    lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def launcher_defaults(existing=None):
    existing = existing or {}
    return {key: existing.get(key, default) for key, default in LAUNCHER_FIELDS}


def ensure_league_files(root=ROOT):
    root = Path(root)
    league_dir = root / "league"
    league_dir.mkdir(exist_ok=True)

    copied = []
    for name in ("drivers.csv", "stats.csv"):
        source = root / "league.example" / name
        target = league_dir / name
        if source.exists() and not target.exists():
            shutil.copyfile(source, target)
            copied.append(str(target))
    return copied


def sanitize_asset_name(path):
    source = Path(path)
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", source.stem).strip("_").lower()
    suffix = source.suffix.lower()
    if not stem:
        stem = "sponsor_logo"
    if suffix not in {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}:
        suffix = ".png"
    return f"{stem}{suffix}"


def install_overlay_brand_graphics(paths, static_dir=STATIC_ASSET_DIR):
    static_dir = Path(static_dir)
    static_dir.mkdir(parents=True, exist_ok=True)
    asset_paths = []

    for raw_path in paths:
        if not raw_path:
            continue
        source = Path(raw_path)
        if not source.exists() or not source.is_file():
            continue

        target = static_dir / sanitize_asset_name(source)
        if source.resolve() != target.resolve():
            shutil.copyfile(source, target)
        asset_paths.append(f"/assets/{target.name}")

    return asset_paths


def format_playlist_paths(paths):
    return ";".join(str(Path(path)) for path in paths if path)


def open_external_link(url):
    webbrowser.open(url)


def broadcast_command():
    return [
        sys.executable,
        str(ROOT / "app.py"),
        "--overlay",
        "--camera-mode",
        "auto",
        "--incident-replay",
        "auto",
    ]


def running_broadcast_pids(root=ROOT):
    app_path = str((Path(root) / "app.py").resolve())
    escaped_app_path = app_path.replace("'", "''")
    script = (
        "Get-CimInstance Win32_Process | "
        f"Where-Object {{ $_.CommandLine -like '*{escaped_app_path}*' }} | "
        "ForEach-Object { $_.ProcessId }"
    )
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", script],
            text=True,
            capture_output=True,
            check=False,
        )
    except Exception:
        return []
    if result.returncode != 0:
        return []
    pids = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.isdigit():
            pids.append(int(line))
    return pids


def is_process_running(process):
    return process is not None and process.poll() is None


def sim_racer_hub_import_command(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    drivers_output="league/drivers.csv",
    career_mode=False,
    dry_run=False,
    drivers_only=False,
):
    command = [
        sys.executable,
        str(ROOT / "tools" / "sim_racer_hub_import.py"),
        source,
        "--bulk",
    ]
    if league_id:
        command.extend(["--league-id", str(league_id)])
    if series_id:
        command.extend(["--series-id", str(series_id)])
    if season_id and not career_mode:
        command.extend(["--season-id", str(season_id)])
    if track_name:
        command.extend(["--track-name", str(track_name)])
    if min_starts:
        command.extend(["--min-starts", str(min_starts)])
    if output:
        command.extend(["--output", str(output)])
    if drivers_only:
        command.append("--drivers-only")
        command.extend(["--drivers-output", str(drivers_output)])
    if dry_run:
        command.append("--dry-run")
    return command


def run_sim_racer_hub_import(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    drivers_output="league/drivers.csv",
    career_mode=False,
    dry_run=False,
    drivers_only=False,
):
    command = sim_racer_hub_import_command(
        source=source,
        league_id=league_id,
        series_id=series_id,
        season_id=season_id,
        track_name=track_name,
        min_starts=min_starts,
        output=output,
        drivers_output=drivers_output,
        career_mode=career_mode,
        dry_run=dry_run,
        drivers_only=drivers_only,
    )
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def launch_broadcast(producer_assist=False):
    global BROADCAST_PROCESS
    if is_process_running(BROADCAST_PROCESS):
        return BROADCAST_PROCESS

    env = os.environ.copy()
    if producer_assist:
        env["USE_OPENAI"] = "false"
        env["USE_ELEVENLABS"] = "false"
    BROADCAST_PROCESS = subprocess.Popen(broadcast_command(), cwd=ROOT, env=env)
    return BROADCAST_PROCESS


def stop_broadcast():
    global BROADCAST_PROCESS
    stopped = False
    if is_process_running(BROADCAST_PROCESS):
        BROADCAST_PROCESS.terminate()
        stopped = True

    external_pids = running_broadcast_pids()
    for pid in external_pids:
        if BROADCAST_PROCESS and BROADCAST_PROCESS.pid == pid:
            continue
        subprocess.run(
            ["taskkill", "/PID", str(pid), "/T", "/F"],
            text=True,
            capture_output=True,
            check=False,
        )
        stopped = True

    if not stopped:
        BROADCAST_PROCESS = None
        return False

    BROADCAST_PROCESS = None
    return True


def run_gui():
    import tkinter as tk
    from tkinter import filedialog
    from tkinter import ttk

    existing = launcher_defaults(load_env_file())
    root = tk.Tk()
    root.title("RGC AI Broadcast Studio")
    root.geometry("1040x720")
    root.minsize(920, 640)
    root.configure(bg=DARK_BG)

    style = ttk.Style(root)
    style.theme_use("clam")
    style.configure("TNotebook", background=DARK_BG, borderwidth=0)
    style.configure(
        "TNotebook.Tab",
        background=PANEL_BG,
        foreground=MUTED_FG,
        padding=(18, 8),
        borderwidth=0,
    )
    style.map(
        "TNotebook.Tab",
        background=[("selected", ACCENT)],
        foreground=[("selected", TEXT_FG)],
    )

    def label(parent, **kwargs):
        defaults = {"bg": kwargs.pop("bg", DARK_BG), "fg": kwargs.pop("fg", TEXT_FG)}
        defaults.update(kwargs)
        return tk.Label(parent, **defaults)

    def frame(parent, **kwargs):
        defaults = {"bg": kwargs.pop("bg", DARK_BG)}
        defaults.update(kwargs)
        return tk.Frame(parent, **defaults)

    def entry(parent, **kwargs):
        defaults = {
            "bg": FIELD_BG,
            "fg": TEXT_FG,
            "insertbackground": TEXT_FG,
            "relief": "flat",
            "highlightthickness": 1,
            "highlightbackground": "#26384c",
            "highlightcolor": ACCENT,
        }
        defaults.update(kwargs)
        return tk.Entry(parent, **defaults)

    def button(parent, text, command, color=ACCENT):
        return tk.Button(
            parent,
            text=text,
            command=command,
            bg=color,
            fg="white",
            activebackground=ACCENT_HOVER,
            activeforeground="white",
            relief="flat",
            padx=12,
            pady=7,
            font=("Segoe UI", 9, "bold"),
        )

    label(
        root,
        text="RGC AI Broadcast Studio",
        font=("Segoe UI", 18, "bold"),
    ).pack(pady=(14, 4))
    label(
        root,
        text="Configure your broadcast, league notes, stats, voices, and overlay.",
        font=("Segoe UI", 10),
        fg=MUTED_FG,
    ).pack(pady=(0, 8))

    link_bar = frame(root)
    link_bar.pack(pady=(0, 8))
    button(
        link_bar,
        text="RGC Discord",
        command=lambda: open_external_link(RGC_DISCORD_URL),
        color="#5865f2",
    ).pack(side="left", padx=5)
    button(
        link_bar,
        text="RGC Website",
        command=lambda: open_external_link(RGC_WEBSITE_URL),
        color="#334b64",
    ).pack(side="left", padx=5)

    status = tk.StringVar(
        value=(
            "Launcher ready. Broadcast is not started from this window yet. "
            f"Settings file: {ENV_PATH}"
        )
    )

    action_bar = frame(root, bg=PANEL_BG)
    action_bar.pack(fill="x", padx=18, pady=(4, 10))

    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=18)

    settings_tab = frame(notebook, bg=PANEL_BG)
    league_tab = frame(notebook, bg=PANEL_BG)
    notebook.add(settings_tab, text="Broadcast Settings")
    notebook.add(league_tab, text="League / Sim Racer Hub")

    settings_frame = frame(settings_tab, bg=PANEL_BG)
    settings_frame.pack(fill="both", expand=True, padx=14, pady=12)

    entries = {}
    for row, (key, _default) in enumerate(LAUNCHER_FIELDS):
        label(settings_frame, text=key, anchor="w", width=24, bg=PANEL_BG, fg=MUTED_FG).grid(
            row=row,
            column=0,
            sticky="w",
            pady=3,
        )
        entry_widget = entry(settings_frame, width=72)
        entry_widget.insert(0, existing.get(key, ""))
        entry_widget.grid(row=row, column=1, sticky="ew", pady=3)
        entries[key] = entry_widget

    def choose_brand_graphics():
        paths = filedialog.askopenfilenames(
            title="Choose sponsor / brand logos for the overlay title",
            filetypes=[
                ("Image files", "*.png *.jpg *.jpeg *.webp *.gif *.svg"),
                ("All files", "*.*"),
            ],
        )
        asset_paths = install_overlay_brand_graphics(paths)
        if not asset_paths:
            status.set("No sponsor logos were copied. Choose PNG, JPG, WEBP, GIF, or SVG files.")
            return
        field = entries["OVERLAY_BRAND_GRAPHICS"]
        field.delete(0, "end")
        field.insert(0, ",".join(asset_paths))
        status.set(f"Added {len(asset_paths)} sponsor logo(s) to the overlay title rotation.")

    def choose_practice_music():
        paths = filedialog.askopenfilenames(
            title="Choose practice music files",
            filetypes=[
                ("Audio files", "*.mp3 *.wav *.m4a *.aac *.flac *.wma"),
                ("All files", "*.*"),
            ],
        )
        if not paths:
            return
        field = entries["PRACTICE_MUSIC_PLAYLIST"]
        field.delete(0, "end")
        field.insert(0, format_playlist_paths(paths))
        status.set(f"Added {len(paths)} practice music file(s). Save settings before starting.")

    def choose_single_audio(field_name, title):
        path = filedialog.askopenfilename(
            title=title,
            filetypes=[
                ("Audio files", "*.mp3 *.wav *.m4a *.aac *.flac *.wma"),
                ("All files", "*.*"),
            ],
        )
        if not path:
            return
        field = entries[field_name]
        field.delete(0, "end")
        field.insert(0, str(Path(path)))
        status.set(f"Set {field_name}. Save settings before starting.")

    button(
        settings_frame,
        text="Choose Sponsor Logos",
        command=choose_brand_graphics,
        color="#334b64",
    ).grid(row=LAUNCHER_FIELDS.index(("USE_SPONSOR_READS", "true")) - 1, column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Anthem Audio",
        command=lambda: choose_single_audio("NATIONAL_ANTHEM_AUDIO", "Choose RGC Anthem audio"),
        color="#334b64",
    ).grid(row=LAUNCHER_FIELDS.index(("NATIONAL_ANTHEM_AUDIO", "")), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Practice Music",
        command=choose_practice_music,
        color="#334b64",
    ).grid(row=LAUNCHER_FIELDS.index(("PRACTICE_MUSIC_PLAYLIST", "")), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Caution Audio",
        command=lambda: choose_single_audio("CAUTION_REPLAY_AUDIO", "Choose caution replay audio"),
        color="#334b64",
    ).grid(row=LAUNCHER_FIELDS.index(("CAUTION_REPLAY_AUDIO", "")), column=2, padx=(8, 0), sticky="w")

    settings_frame.columnconfigure(1, weight=1)

    label(root, textvariable=status, anchor="w", fg=MUTED_FG).pack(
        fill="x",
        padx=18,
        pady=(8, 0),
    )

    def collect_values():
        return {key: entry.get().strip() for key, entry in entries.items()}

    def save_settings():
        save_env_file(collect_values())
        status.set(f"Saved settings to {ENV_PATH}")

    def create_league_files():
        copied = ensure_league_files()
        if copied:
            messagebox.showinfo("League files created", "\n".join(copied))
        else:
            messagebox.showinfo(
                "League files ready",
                "league/drivers.csv and league/stats.csv already exist.",
            )

    def start_full_ai():
        save_settings()
        process = launch_broadcast(producer_assist=False)
        if process:
            status.set("Started full AI broadcast with overlay, cameras, and incident replay.")

    def start_producer_assist():
        save_settings()
        process = launch_broadcast(producer_assist=True)
        if process:
            status.set(
                "Started Producer Assist broadcast with overlay and cameras. "
                "AI voices are disabled so a human broadcaster can call the race."
            )

    def stop_running_broadcast():
        if stop_broadcast():
            status.set("Stopped broadcast.")
        else:
            status.set("No running broadcast found from this launcher.")

    button(action_bar, text="Save Settings", command=save_settings, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Create League Files", command=create_league_files, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Start Broadcast", command=start_full_ai, color=GREEN).pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Start Producer Assist", command=start_producer_assist, color=ACCENT).pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Stop Broadcast", command=stop_running_broadcast, color=STOP_RED).pack(
        side="left",
        padx=6,
        pady=8,
    )

    build_league_tab(league_tab, status, label, frame, entry, button)

    root.mainloop()


def build_league_tab(parent, status, label, frame, entry, button):
    import tkinter as tk

    intro = (
        "Import league stats from Sim Racer Hub. You can use the clean URL "
        "https://simracerhub.com with League, Series, and Season IDs. "
        "Track history is optional and only helps pre-load driver stats for an upcoming track."
    )
    label(parent, text=intro, anchor="w", justify="left", wraplength=900, bg=PANEL_BG, fg=MUTED_FG).pack(
        fill="x",
        padx=14,
        pady=(10, 8),
    )

    form = frame(parent, bg=PANEL_BG)
    form.pack(fill="x", padx=14)

    defaults = {
        "source": "https://simracerhub.com",
        "league_id": "1598",
        "series_id": "3872",
        "season_id": "29247",
        "track_name": "",
        "min_starts": "2",
        "output": "league/stats.csv",
        "drivers_output": "league/drivers.csv",
    }
    entries = {}
    rows = [
        ("Sim Racer Hub URL", "source"),
        ("League ID", "league_id"),
        ("Series ID", "series_id"),
        ("Season ID", "season_id"),
        ("Track History Filter", "track_name"),
        ("Minimum Starts", "min_starts"),
        ("Stats Output CSV", "output"),
        ("Drivers Output CSV", "drivers_output"),
    ]
    for row_number, (label_text, key) in enumerate(rows):
        label(form, text=label_text, anchor="w", width=22, bg=PANEL_BG, fg=MUTED_FG).grid(
            row=row_number,
            column=0,
            sticky="w",
            pady=4,
        )
        entry_widget = entry(form, width=86)
        entry_widget.insert(0, defaults[key])
        entry_widget.grid(row=row_number, column=1, sticky="ew", pady=4)
        entries[key] = entry_widget
    form.columnconfigure(1, weight=1)

    career_mode = tk.BooleanVar(value=False)
    tk.Checkbutton(
        form,
        text="Career Mode: import all seasons in this series instead of one season",
        variable=career_mode,
        bg=PANEL_BG,
        fg=TEXT_FG,
        activebackground=PANEL_BG,
        activeforeground=TEXT_FG,
        selectcolor=FIELD_BG,
    ).grid(row=len(rows), column=1, sticky="w", pady=(4, 8))

    output_box = tk.Text(
        parent,
        height=18,
        wrap="none",
        bg="#08111a",
        fg=TEXT_FG,
        insertbackground=TEXT_FG,
        relief="flat",
        highlightthickness=1,
        highlightbackground="#26384c",
    )
    output_box.pack(fill="both", expand=True, padx=14, pady=(8, 0))

    def values():
        return {key: entry.get().strip() for key, entry in entries.items()}

    def set_output(text):
        output_box.delete("1.0", "end")
        output_box.insert("1.0", text)

    def run_import(dry_run, drivers_only=False):
        data = values()
        if not data["source"]:
            messagebox.showerror("Missing URL", "Paste a Sim Racer Hub URL first.")
            return

        result = run_sim_racer_hub_import(
            source=data["source"],
            league_id=data["league_id"],
            series_id=data["series_id"],
            season_id=data["season_id"],
            track_name=data["track_name"],
            min_starts=data["min_starts"],
            output=data["output"],
            drivers_output=data["drivers_output"],
            career_mode=career_mode.get(),
            dry_run=dry_run,
            drivers_only=drivers_only,
        )
        combined_output = result.stdout
        if result.stderr:
            combined_output += "\n" + result.stderr
        set_output(combined_output or "(No output)")
        if result.returncode == 0:
            action = "Previewed" if dry_run else "Imported"
            mode = "career" if career_mode.get() else "season"
            if drivers_only:
                target = data["drivers_output"] or "league/drivers.csv"
            else:
                target = data["output"] or "league/stats.csv"
            data_type = "driver roster" if drivers_only else "stats"
            suffix = "" if dry_run else f" to {target}"
            status.set(f"{action} Sim Racer Hub {mode} {data_type}{suffix}.")
        else:
            status.set("Sim Racer Hub import failed. Check the output panel.")

    buttons = frame(parent, bg=PANEL_BG)
    buttons.pack(fill="x", padx=14, pady=10)
    button(buttons, text="Preview Stats", command=lambda: run_import(True), color="#334b64").pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Import Stats", command=lambda: run_import(False), color=GREEN).pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Preview Driver Roster", command=lambda: run_import(True, True), color="#334b64").pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Import Driver Roster", command=lambda: run_import(False, True), color=GREEN).pack(
        side="left",
        padx=4,
    )
    label(
        buttons,
        text="Tip: leave Track History blank for general stats; use Career Mode for all seasons.",
        anchor="w",
        bg=PANEL_BG,
        fg=MUTED_FG,
    ).pack(side="left", padx=12)


def main():
    run_gui()


if __name__ == "__main__":
    main()
