from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from tkinter import messagebox


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"

LAUNCHER_FIELDS = [
    ("USE_OPENAI", "true"),
    ("OPENAI_API_KEY", ""),
    ("OPENAI_MODEL", "gpt-5.5"),
    ("USE_ELEVENLABS", "true"),
    ("ELEVENLABS_API_KEY", ""),
    ("LEAD_VOICE_ID", ""),
    ("COLOR_VOICE_ID", ""),
    ("PIT_VOICE_ID", ""),
    ("OVERLAY_EVENT_TITLE", "RGC AI Broadcast"),
    ("OVERLAY_RACE_SPONSOR", ""),
    ("OVERLAY_SERIES_NAME", ""),
    ("USE_SPONSOR_READS", "true"),
    ("SPONSOR_READ_NAME", ""),
    ("SPONSOR_READ_CAUSE", ""),
    ("USE_LEAGUE_DRIVER_NOTES", "false"),
    ("LEAGUE_DRIVERS_CSV", "league/drivers.csv"),
    ("LEAGUE_STATS_CSV", "league/stats.csv"),
]


def load_env_file(path=ENV_PATH):
    values = {}
    path = Path(path)
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def save_env_file(values, path=ENV_PATH):
    lines = [
        "# Generated by RGC AI Broadcast Studio launcher.",
        "# You can still edit this file manually if needed.",
        "",
    ]
    for key, default in LAUNCHER_FIELDS:
        lines.append(f"{key}={values.get(key, default)}")
    lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def launcher_defaults(existing=None):
    existing = existing or {}
    return {key: existing.get(key, default) for key, default in LAUNCHER_FIELDS}


def ensure_league_files(root=ROOT):
    root = Path(root)
    league_dir = root / "league"
    league_dir.mkdir(exist_ok=True)

    copied = []
    for name in ("drivers.csv", "stats.csv"):
        source = root / "league.example" / name
        target = league_dir / name
        if source.exists() and not target.exists():
            shutil.copyfile(source, target)
            copied.append(str(target))
    return copied


def broadcast_command():
    return [
        sys.executable,
        str(ROOT / "app.py"),
        "--overlay",
        "--camera-mode",
        "auto",
        "--incident-replay",
        "auto",
    ]


def sim_racer_hub_import_command(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    career_mode=False,
    dry_run=False,
):
    command = [
        sys.executable,
        str(ROOT / "tools" / "sim_racer_hub_import.py"),
        source,
        "--bulk",
    ]
    if league_id:
        command.extend(["--league-id", str(league_id)])
    if series_id:
        command.extend(["--series-id", str(series_id)])
    if season_id and not career_mode:
        command.extend(["--season-id", str(season_id)])
    if track_name:
        command.extend(["--track-name", str(track_name)])
    if min_starts:
        command.extend(["--min-starts", str(min_starts)])
    if output:
        command.extend(["--output", str(output)])
    if dry_run:
        command.append("--dry-run")
    return command


def run_sim_racer_hub_import(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    career_mode=False,
    dry_run=False,
):
    command = sim_racer_hub_import_command(
        source=source,
        league_id=league_id,
        series_id=series_id,
        season_id=season_id,
        track_name=track_name,
        min_starts=min_starts,
        output=output,
        career_mode=career_mode,
        dry_run=dry_run,
    )
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def launch_broadcast(helper_mode=False):
    env = os.environ.copy()
    if helper_mode:
        env["USE_OPENAI"] = "false"
        env["USE_ELEVENLABS"] = "false"
    subprocess.Popen(broadcast_command(), cwd=ROOT, env=env)


def run_gui():
    import tkinter as tk
    from tkinter import ttk

    existing = launcher_defaults(load_env_file())
    root = tk.Tk()
    root.title("RGC AI Broadcast Studio")
    root.geometry("940x780")

    tk.Label(
        root,
        text="RGC AI Broadcast Studio",
        font=("Segoe UI", 18, "bold"),
    ).pack(pady=(14, 4))
    tk.Label(
        root,
        text="Configure your broadcast, league notes, stats, voices, and overlay.",
        font=("Segoe UI", 10),
    ).pack(pady=(0, 10))

    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=18)

    settings_tab = tk.Frame(notebook)
    league_tab = tk.Frame(notebook)
    notebook.add(settings_tab, text="Broadcast Settings")
    notebook.add(league_tab, text="League / Sim Racer Hub")

    frame = tk.Frame(settings_tab)
    frame.pack(fill="both", expand=True, padx=4, pady=8)

    entries = {}
    for row, (key, _default) in enumerate(LAUNCHER_FIELDS):
        tk.Label(frame, text=key, anchor="w", width=24).grid(
            row=row,
            column=0,
            sticky="w",
            pady=3,
        )
        entry = tk.Entry(frame, width=70)
        entry.insert(0, existing.get(key, ""))
        entry.grid(row=row, column=1, sticky="ew", pady=3)
        entries[key] = entry

    frame.columnconfigure(1, weight=1)

    status = tk.StringVar(value=f"Settings file: {ENV_PATH}")
    tk.Label(root, textvariable=status, anchor="w").pack(fill="x", padx=18, pady=(8, 0))

    def collect_values():
        return {key: entry.get().strip() for key, entry in entries.items()}

    def save_settings():
        save_env_file(collect_values())
        status.set(f"Saved settings to {ENV_PATH}")

    def create_league_files():
        copied = ensure_league_files()
        if copied:
            messagebox.showinfo("League files created", "\n".join(copied))
        else:
            messagebox.showinfo(
                "League files ready",
                "league/drivers.csv and league/stats.csv already exist.",
            )

    def start_full_ai():
        save_settings()
        launch_broadcast(helper_mode=False)
        status.set("Started full AI broadcast.")

    def start_helper():
        save_settings()
        launch_broadcast(helper_mode=True)
        status.set("Started broadcast helper mode. OpenAI and ElevenLabs are disabled.")

    buttons = tk.Frame(root)
    buttons.pack(fill="x", padx=18, pady=16)
    tk.Button(buttons, text="Save Settings", command=save_settings).pack(
        side="left",
        padx=4,
    )
    tk.Button(buttons, text="Create League Files", command=create_league_files).pack(
        side="left",
        padx=4,
    )
    tk.Button(buttons, text="Start Full AI Broadcast", command=start_full_ai).pack(
        side="left",
        padx=4,
    )
    tk.Button(buttons, text="Start Broadcast Helper", command=start_helper).pack(
        side="left",
        padx=4,
    )

    build_league_tab(league_tab, status)

    root.mainloop()


def build_league_tab(parent, status):
    import tkinter as tk
    from tkinter import ttk

    intro = (
        "Import league stats from Sim Racer Hub. Use Season Mode for the current season, "
        "or Career Mode for all seasons on the series page."
    )
    tk.Label(parent, text=intro, anchor="w", justify="left", wraplength=860).pack(
        fill="x",
        padx=8,
        pady=(10, 8),
    )

    form = tk.Frame(parent)
    form.pack(fill="x", padx=8)

    defaults = {
        "source": "https://simracerhub.com/series_seasons.php?series_id=3872&reset_series=y",
        "league_id": "1598",
        "series_id": "3872",
        "season_id": "29247",
        "track_name": "",
        "min_starts": "2",
        "output": "league/stats.csv",
    }
    entries = {}
    rows = [
        ("Sim Racer Hub URL", "source"),
        ("League ID", "league_id"),
        ("Series ID", "series_id"),
        ("Season ID", "season_id"),
        ("Upcoming Track Name", "track_name"),
        ("Minimum Starts", "min_starts"),
        ("Output CSV", "output"),
    ]
    for row_number, (label, key) in enumerate(rows):
        tk.Label(form, text=label, anchor="w", width=22).grid(
            row=row_number,
            column=0,
            sticky="w",
            pady=4,
        )
        entry = tk.Entry(form, width=86)
        entry.insert(0, defaults[key])
        entry.grid(row=row_number, column=1, sticky="ew", pady=4)
        entries[key] = entry
    form.columnconfigure(1, weight=1)

    career_mode = tk.BooleanVar(value=False)
    tk.Checkbutton(
        form,
        text="Career Mode: import all seasons in this series instead of one season",
        variable=career_mode,
    ).grid(row=len(rows), column=1, sticky="w", pady=(4, 8))

    output_box = tk.Text(parent, height=18, wrap="none")
    output_box.pack(fill="both", expand=True, padx=8, pady=(8, 0))

    def values():
        return {key: entry.get().strip() for key, entry in entries.items()}

    def set_output(text):
        output_box.delete("1.0", "end")
        output_box.insert("1.0", text)

    def run_import(dry_run):
        data = values()
        if not data["source"]:
            messagebox.showerror("Missing URL", "Paste a Sim Racer Hub URL first.")
            return

        result = run_sim_racer_hub_import(
            source=data["source"],
            league_id=data["league_id"],
            series_id=data["series_id"],
            season_id=data["season_id"],
            track_name=data["track_name"],
            min_starts=data["min_starts"],
            output=data["output"],
            career_mode=career_mode.get(),
            dry_run=dry_run,
        )
        combined_output = result.stdout
        if result.stderr:
            combined_output += "\n" + result.stderr
        set_output(combined_output or "(No output)")
        if result.returncode == 0:
            action = "Previewed" if dry_run else "Imported"
            mode = "career" if career_mode.get() else "season"
            status.set(f"{action} Sim Racer Hub {mode} stats.")
        else:
            status.set("Sim Racer Hub import failed. Check the output panel.")

    buttons = tk.Frame(parent)
    buttons.pack(fill="x", padx=8, pady=10)
    tk.Button(buttons, text="Preview Import", command=lambda: run_import(True)).pack(
        side="left",
        padx=4,
    )
    tk.Button(buttons, text="Import to league/stats.csv", command=lambda: run_import(False)).pack(
        side="left",
        padx=4,
    )
    tk.Label(
        buttons,
        text="Tip: leave Season ID blank or check Career Mode to use all seasons.",
        anchor="w",
    ).pack(side="left", padx=12)


def main():
    run_gui()


if __name__ == "__main__":
    main()
