from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path
from tkinter import messagebox


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
STATIC_ASSET_DIR = ROOT / "production" / "static"
RUNTIME_DIR = ROOT / ".runtime"
BROADCAST_PID_PATH = RUNTIME_DIR / "broadcast.pid"
PROFILE_DIR = ROOT / "profiles"
BROADCAST_PROCESS = None
RGC_DISCORD_URL = "https://discord.gg/Axwwa8CUqt"
RGC_WEBSITE_URL = "https://www.realisticgamingcrew.com"
DEFAULT_OVERLAY_URL = "http://127.0.0.1:8765/overlay"

DARK_BG = "#071018"
PANEL_BG = "#101a24"
FIELD_BG = "#172331"
TEXT_FG = "#f4f7fb"
MUTED_FG = "#9fb0c2"
ACCENT = "#8b1e2d"
ACCENT_HOVER = "#a72a3a"
GREEN = "#158a4d"
STOP_RED = "#b73535"

LAUNCHER_FIELDS = [
    ("USE_OPENAI", "true"),
    ("OPENAI_API_KEY", ""),
    ("OPENAI_MODEL", "gpt-5.5"),
    ("USE_ELEVENLABS", "true"),
    ("ELEVENLABS_API_KEY", ""),
    ("LEAD_VOICE_ID", ""),
    ("COLOR_VOICE_ID", ""),
    ("PIT_VOICE_ID", ""),
    ("OVERLAY_EVENT_TITLE", "RGC AI Broadcast"),
    ("OVERLAY_RACE_SPONSOR", ""),
    ("OVERLAY_SERIES_NAME", ""),
    (
        "OVERLAY_BRAND_GRAPHICS",
        "/assets/rgc_motorsports.png,/assets/autism_awareness.png,/assets/keep_it_real.webp",
    ),
    ("USE_SPONSOR_READS", "true"),
    ("SPONSOR_READ_NAME", ""),
    ("SPONSOR_READ_CAUSE", ""),
    ("USE_NATIONAL_ANTHEM", "false"),
    ("NATIONAL_ANTHEM_AUDIO", ""),
    ("NATIONAL_ANTHEM_GRAPHICS", ""),
    ("PRACTICE_MUSIC_PLAYLIST", ""),
    ("STUDIO_VOLUME", "65"),
    ("CAUTION_REPLAY_AUDIO", ""),
    ("CAUTION_PRESENTATION_GRAPHICS", ""),
    ("POST_RACE_INTERVIEWS_ENABLED", "false"),
    ("POST_RACE_FINISH_CAMERA_DELAY_SECONDS", "180"),
    ("USE_LEAGUE_DRIVER_NOTES", "false"),
    ("LEAGUE_DRIVERS_CSV", "league/drivers.csv"),
    ("LEAGUE_STATS_CSV", "league/stats.csv"),
]


def load_env_file(path=ENV_PATH):
    values = {}
    path = Path(path)
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def save_env_file(values, path=ENV_PATH):
    lines = [
        "# Generated by RGC AI Broadcast Studio launcher.",
        "# You can still edit this file manually if needed.",
        "",
    ]
    for key, default in LAUNCHER_FIELDS:
        lines.append(f"{key}={values.get(key, default)}")
    lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def sanitize_profile_name(name):
    cleaned = re.sub(r"[^A-Za-z0-9 _.-]+", "", str(name or "")).strip()
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned[:60]


def profile_path(profile_name, profile_dir=PROFILE_DIR):
    safe_name = sanitize_profile_name(profile_name)
    if not safe_name:
        raise ValueError("Profile name is required.")
    filename = safe_name.replace(" ", "_")
    return Path(profile_dir) / f"{filename}.env"


def list_profiles(profile_dir=PROFILE_DIR):
    profile_dir = Path(profile_dir)
    if not profile_dir.exists():
        return []
    names = []
    for path in sorted(profile_dir.glob("*.env")):
        names.append(path.stem.replace("_", " "))
    return names


def save_profile(profile_name, values, profile_dir=PROFILE_DIR):
    path = profile_path(profile_name, profile_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    save_env_file(values, path)
    return path


def load_profile(profile_name, profile_dir=PROFILE_DIR):
    path = profile_path(profile_name, profile_dir)
    if not path.exists():
        raise FileNotFoundError(f"Profile not found: {profile_name}")
    return launcher_defaults(load_env_file(path))


def launcher_defaults(existing=None):
    existing = existing or {}
    defaults = {key: existing.get(key, default) for key, default in LAUNCHER_FIELDS}
    if "STUDIO_VOLUME" not in existing and "PRACTICE_MUSIC_VOLUME" in existing:
        defaults["STUDIO_VOLUME"] = existing["PRACTICE_MUSIC_VOLUME"]
    return defaults


def setting_enabled(values, key, default="false"):
    return str(values.get(key, default) or default).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def resolve_project_path(path_value, root=ROOT):
    path = Path(str(path_value or "").strip())
    if not path:
        return Path(root)
    if path.is_absolute():
        return path
    return Path(root) / path


def build_health_status(values, root=ROOT, broadcast_running=False):
    """Return launcher health rows as (name, state, detail, level)."""

    rows = []

    if setting_enabled(values, "USE_OPENAI", "true"):
        if values.get("OPENAI_API_KEY"):
            rows.append(("OpenAI", "Ready", values.get("OPENAI_MODEL", "Configured"), "ok"))
        else:
            rows.append(("OpenAI", "Needs key", "Add OPENAI_API_KEY or turn OpenAI off.", "warn"))
    else:
        rows.append(("OpenAI", "Off", "AI commentary generation disabled.", "off"))

    if setting_enabled(values, "USE_ELEVENLABS", "true"):
        missing = []
        if not values.get("ELEVENLABS_API_KEY"):
            missing.append("API key")
        if not values.get("LEAD_VOICE_ID"):
            missing.append("lead voice")
        if not values.get("COLOR_VOICE_ID"):
            missing.append("Jeff voice")
        if not values.get("PIT_VOICE_ID"):
            missing.append("Sarah voice")
        if missing:
            rows.append(
                (
                    "ElevenLabs",
                    "Needs setup",
                    f"Missing {', '.join(missing)}.",
                    "warn",
                )
            )
        else:
            rows.append(("ElevenLabs", "Ready", "All broadcaster voices configured.", "ok"))
    else:
        rows.append(("ElevenLabs", "Off", "Voice playback disabled.", "off"))

    rows.append(("Overlay", "Ready", DEFAULT_OVERLAY_URL, "ok"))

    if setting_enabled(values, "USE_LEAGUE_DRIVER_NOTES", "false"):
        drivers_path = resolve_project_path(values.get("LEAGUE_DRIVERS_CSV"), root)
        stats_path = resolve_project_path(values.get("LEAGUE_STATS_CSV"), root)
        missing_files = [
            label
            for label, path in (("drivers", drivers_path), ("stats", stats_path))
            if not path.exists()
        ]
        if missing_files:
            rows.append(
                (
                    "League Notes",
                    "Needs files",
                    f"Missing {', '.join(missing_files)} CSV file(s).",
                    "warn",
                )
            )
        else:
            rows.append(("League Notes", "Ready", "Driver and stats CSV files found.", "ok"))
    else:
        rows.append(("League Notes", "Off", "League driver context disabled.", "off"))

    if values.get("PRACTICE_MUSIC_PLAYLIST"):
        songs = [
            path
            for path in str(values.get("PRACTICE_MUSIC_PLAYLIST", "")).split(";")
            if path.strip()
        ]
        existing_songs = [path for path in songs if Path(path).expanduser().exists()]
        if existing_songs:
            rows.append(("Practice Music", "Ready", f"{len(existing_songs)} song(s) found.", "ok"))
        else:
            rows.append(("Practice Music", "Check files", "Playlist is set, but no song files were found.", "warn"))
    else:
        rows.append(("Practice Music", "Off", "No practice playlist selected.", "off"))

    if broadcast_running:
        rows.append(("Broadcast", "Running", "Use Stop Broadcast before closing.", "ok"))
    else:
        rows.append(("Broadcast", "Stopped", "Ready to start when iRacing is open.", "off"))

    return rows


def ensure_league_files(root=ROOT):
    root = Path(root)
    league_dir = root / "league"
    league_dir.mkdir(exist_ok=True)

    copied = []
    for name in ("drivers.csv", "stats.csv"):
        source = root / "league.example" / name
        target = league_dir / name
        if source.exists() and not target.exists():
            shutil.copyfile(source, target)
            copied.append(str(target))
    return copied


def sanitize_asset_name(path):
    source = Path(path)
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", source.stem).strip("_").lower()
    suffix = source.suffix.lower()
    if not stem:
        stem = "sponsor_logo"
    if suffix not in {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}:
        suffix = ".png"
    return f"{stem}{suffix}"


def install_overlay_brand_graphics(paths, static_dir=STATIC_ASSET_DIR):
    static_dir = Path(static_dir)
    static_dir.mkdir(parents=True, exist_ok=True)
    asset_paths = []

    for raw_path in paths:
        if not raw_path:
            continue
        source = Path(raw_path)
        if not source.exists() or not source.is_file():
            continue

        target = static_dir / sanitize_asset_name(source)
        if source.resolve() != target.resolve():
            shutil.copyfile(source, target)
        asset_paths.append(f"/assets/{target.name}")

    return asset_paths


def format_playlist_paths(paths):
    return ";".join(str(Path(path)) for path in paths if path)


def apply_audio_file_selection(values, field_name, path):
    values[field_name] = str(Path(path))
    if field_name == "NATIONAL_ANTHEM_AUDIO":
        values["USE_NATIONAL_ANTHEM"] = "true"
    return values


def open_external_link(url):
    webbrowser.open(url)


def copy_to_clipboard(root, text):
    root.clipboard_clear()
    root.clipboard_append(text)
    root.update()


def broadcast_command():
    return [
        sys.executable,
        str(ROOT / "app.py"),
        "--overlay",
        "--camera-mode",
        "auto",
        "--incident-replay",
        "auto",
    ]


def write_broadcast_pid(pid, path=BROADCAST_PID_PATH):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(str(int(pid)), encoding="utf-8")


def read_broadcast_pid(path=BROADCAST_PID_PATH):
    path = Path(path)
    if not path.exists():
        return None
    try:
        pid = int(path.read_text(encoding="utf-8").strip())
    except Exception:
        return None
    return pid if pid > 0 else None


def clear_broadcast_pid(path=BROADCAST_PID_PATH):
    try:
        Path(path).unlink(missing_ok=True)
    except Exception:
        pass


def running_broadcast_pids(root=ROOT):
    root_path = str(Path(root).resolve())
    app_path = str((Path(root) / "app.py").resolve())
    escaped_root_path = root_path.replace("'", "''")
    escaped_app_path = app_path.replace("'", "''")
    script = (
        "Get-CimInstance Win32_Process | "
        "Where-Object { "
        f"($_.CommandLine -like '*{escaped_app_path}*') -or "
        f"(($_.CommandLine -like '*app.py*') -and ($_.CommandLine -like '*{escaped_root_path}*')) "
        "} | "
        "ForEach-Object { $_.ProcessId }"
    )
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", script],
            text=True,
            capture_output=True,
            check=False,
        )
    except Exception:
        return []
    if result.returncode != 0:
        return []
    pids = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.isdigit():
            pids.append(int(line))
    return pids


def stop_broadcast_processes(pids):
    stopped = 0
    for pid in pids:
        result = subprocess.run(
            ["taskkill", "/PID", str(pid), "/T", "/F"],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            stopped += 1
    return stopped


def is_process_running(process):
    return process is not None and process.poll() is None


def sim_racer_hub_import_command(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    drivers_output="league/drivers.csv",
    career_mode=False,
    dry_run=False,
    drivers_only=False,
):
    command = [
        sys.executable,
        str(ROOT / "tools" / "sim_racer_hub_import.py"),
        source,
        "--bulk",
    ]
    if league_id:
        command.extend(["--league-id", str(league_id)])
    if series_id:
        command.extend(["--series-id", str(series_id)])
    if season_id and not career_mode:
        command.extend(["--season-id", str(season_id)])
    if track_name:
        command.extend(["--track-name", str(track_name)])
    if min_starts:
        command.extend(["--min-starts", str(min_starts)])
    if output:
        command.extend(["--output", str(output)])
    if drivers_only:
        command.append("--drivers-only")
        command.extend(["--drivers-output", str(drivers_output)])
    if dry_run:
        command.append("--dry-run")
    return command


def run_sim_racer_hub_import(
    source,
    league_id="",
    series_id="",
    season_id="",
    track_name="",
    min_starts="1",
    output="league/stats.csv",
    drivers_output="league/drivers.csv",
    career_mode=False,
    dry_run=False,
    drivers_only=False,
):
    command = sim_racer_hub_import_command(
        source=source,
        league_id=league_id,
        series_id=series_id,
        season_id=season_id,
        track_name=track_name,
        min_starts=min_starts,
        output=output,
        drivers_output=drivers_output,
        career_mode=career_mode,
        dry_run=dry_run,
        drivers_only=drivers_only,
    )
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def launch_broadcast(producer_assist=False):
    global BROADCAST_PROCESS
    if is_process_running(BROADCAST_PROCESS):
        return BROADCAST_PROCESS

    env = os.environ.copy()
    if producer_assist:
        env["USE_OPENAI"] = "false"
        env["USE_ELEVENLABS"] = "false"
    BROADCAST_PROCESS = subprocess.Popen(broadcast_command(), cwd=ROOT, env=env)
    write_broadcast_pid(BROADCAST_PROCESS.pid)
    return BROADCAST_PROCESS


def stop_broadcast():
    global BROADCAST_PROCESS
    pids_to_stop = []
    if is_process_running(BROADCAST_PROCESS):
        pids_to_stop.append(BROADCAST_PROCESS.pid)

    saved_pid = read_broadcast_pid()
    if saved_pid:
        pids_to_stop.append(saved_pid)

    external_pids = running_broadcast_pids()
    for pid in external_pids:
        pids_to_stop.append(pid)
    pids_to_stop = sorted(set(pid for pid in pids_to_stop if pid))
    stopped_count = stop_broadcast_processes(pids_to_stop)

    clear_broadcast_pid()
    BROADCAST_PROCESS = None
    return stopped_count


def has_running_broadcast():
    return (
        is_process_running(BROADCAST_PROCESS)
        or bool(read_broadcast_pid())
        or bool(running_broadcast_pids())
    )


def run_gui():
    import tkinter as tk
    from tkinter import filedialog
    from tkinter import ttk

    existing = launcher_defaults(load_env_file())
    root = tk.Tk()
    root.title("RGC AI Broadcast Studio")
    root.geometry("1040x720")
    root.minsize(920, 640)
    root.configure(bg=DARK_BG)

    style = ttk.Style(root)
    style.theme_use("clam")
    style.configure("TNotebook", background=DARK_BG, borderwidth=0)
    style.configure(
        "TNotebook.Tab",
        background=PANEL_BG,
        foreground=MUTED_FG,
        padding=(18, 8),
        borderwidth=0,
    )
    style.map(
        "TNotebook.Tab",
        background=[("selected", ACCENT)],
        foreground=[("selected", TEXT_FG)],
    )

    def label(parent, **kwargs):
        defaults = {"bg": kwargs.pop("bg", DARK_BG), "fg": kwargs.pop("fg", TEXT_FG)}
        defaults.update(kwargs)
        return tk.Label(parent, **defaults)

    def frame(parent, **kwargs):
        defaults = {"bg": kwargs.pop("bg", DARK_BG)}
        defaults.update(kwargs)
        return tk.Frame(parent, **defaults)

    def entry(parent, **kwargs):
        defaults = {
            "bg": FIELD_BG,
            "fg": TEXT_FG,
            "insertbackground": TEXT_FG,
            "relief": "flat",
            "highlightthickness": 1,
            "highlightbackground": "#26384c",
            "highlightcolor": ACCENT,
        }
        defaults.update(kwargs)
        return tk.Entry(parent, **defaults)

    def button(parent, text, command, color=ACCENT):
        return tk.Button(
            parent,
            text=text,
            command=command,
            bg=color,
            fg="white",
            activebackground=ACCENT_HOVER,
            activeforeground="white",
            relief="flat",
            padx=12,
            pady=7,
            font=("Segoe UI", 9, "bold"),
        )

    def scrollable_tab(parent):
        container = frame(parent, bg=PANEL_BG)
        container.pack(fill="both", expand=True)

        canvas = tk.Canvas(
            container,
            bg=PANEL_BG,
            borderwidth=0,
            highlightthickness=0,
        )
        scrollbar = tk.Scrollbar(container, orient="vertical", command=canvas.yview)
        content = frame(canvas, bg=PANEL_BG)
        window_id = canvas.create_window((0, 0), window=content, anchor="nw")

        def update_scroll_region(_event=None):
            canvas.configure(scrollregion=canvas.bbox("all"))

        def resize_content(event):
            canvas.itemconfigure(window_id, width=event.width)

        def enable_mousewheel(_event=None):
            canvas.bind_all("<MouseWheel>", on_mousewheel)

        def disable_mousewheel(_event=None):
            canvas.unbind_all("<MouseWheel>")

        def on_mousewheel(event):
            delta = int(-1 * (event.delta / 120))
            canvas.yview_scroll(delta, "units")

        content.bind("<Configure>", update_scroll_region)
        canvas.bind("<Configure>", resize_content)
        content.bind("<Enter>", enable_mousewheel)
        content.bind("<Leave>", disable_mousewheel)
        canvas.configure(yscrollcommand=scrollbar.set)

        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        return content

    label(
        root,
        text="RGC AI Broadcast Studio",
        font=("Segoe UI", 18, "bold"),
    ).pack(pady=(14, 4))
    label(
        root,
        text="Configure your broadcast, league notes, stats, voices, and overlay.",
        font=("Segoe UI", 10),
        fg=MUTED_FG,
    ).pack(pady=(0, 8))

    link_bar = frame(root)
    link_bar.pack(pady=(0, 8))
    button(
        link_bar,
        text="RGC Discord",
        command=lambda: open_external_link(RGC_DISCORD_URL),
        color="#5865f2",
    ).pack(side="left", padx=5)
    button(
        link_bar,
        text="RGC Website",
        command=lambda: open_external_link(RGC_WEBSITE_URL),
        color="#334b64",
    ).pack(side="left", padx=5)

    status = tk.StringVar(
        value=(
            "Launcher ready. Broadcast is not started from this window yet. "
            f"Settings file: {ENV_PATH}"
        )
    )

    profile_bar = frame(root, bg=PANEL_BG)
    profile_bar.pack(fill="x", padx=18, pady=(0, 8))
    label(
        profile_bar,
        text="Profile",
        bg=PANEL_BG,
        fg=MUTED_FG,
        font=("Segoe UI", 9, "bold"),
    ).pack(side="left", padx=(10, 6), pady=8)
    profile_var = tk.StringVar(value="")
    profile_combo = ttk.Combobox(
        profile_bar,
        textvariable=profile_var,
        values=list_profiles(),
        width=28,
    )
    profile_combo.pack(side="left", padx=4, pady=8)
    label(
        profile_bar,
        text="New / Save As",
        bg=PANEL_BG,
        fg=MUTED_FG,
    ).pack(side="left", padx=(14, 6), pady=8)
    profile_name_var = tk.StringVar(value="")
    profile_name_entry = entry(profile_bar, textvariable=profile_name_var, width=24)
    profile_name_entry.pack(side="left", padx=4, pady=8)

    action_bar = frame(root, bg=PANEL_BG)
    action_bar.pack(fill="x", padx=18, pady=(4, 10))

    health_panel = frame(root, bg=PANEL_BG)
    health_panel.pack(fill="x", padx=18, pady=(0, 10))
    health_header = frame(health_panel, bg=PANEL_BG)
    health_header.pack(fill="x", padx=12, pady=(10, 4))
    label(
        health_header,
        text="Broadcast Health",
        bg=PANEL_BG,
        fg=TEXT_FG,
        font=("Segoe UI", 11, "bold"),
    ).pack(side="left")
    health_summary = tk.StringVar(value="Not checked yet.")
    label(
        health_header,
        textvariable=health_summary,
        bg=PANEL_BG,
        fg=MUTED_FG,
    ).pack(side="left", padx=(12, 0))
    health_rows_frame = frame(health_panel, bg=PANEL_BG)
    health_rows_frame.pack(fill="x", padx=12, pady=(0, 10))
    health_row_widgets = []

    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=18)

    settings_tab = frame(notebook, bg=PANEL_BG)
    league_tab = frame(notebook, bg=PANEL_BG)
    notebook.add(settings_tab, text="Broadcast Settings")
    notebook.add(league_tab, text="League / Sim Racer Hub")

    settings_content = scrollable_tab(settings_tab)
    league_content = scrollable_tab(league_tab)

    settings_frame = frame(settings_content, bg=PANEL_BG)
    settings_frame.pack(fill="both", expand=True, padx=14, pady=12)

    entries = {}
    overlay_brand_row = LAUNCHER_FIELDS.index(
        (
            "OVERLAY_BRAND_GRAPHICS",
            "/assets/rgc_motorsports.png,/assets/autism_awareness.png,/assets/keep_it_real.webp",
        )
    )
    overlay_link_row = overlay_brand_row + 1

    def settings_grid_row(field_row):
        return field_row + 1 if field_row > overlay_brand_row else field_row

    for row, (key, _default) in enumerate(LAUNCHER_FIELDS):
        if key == "STUDIO_VOLUME":
            continue
        grid_row = settings_grid_row(row)
        label(settings_frame, text=key, anchor="w", width=24, bg=PANEL_BG, fg=MUTED_FG).grid(
            row=grid_row,
            column=0,
            sticky="w",
            pady=3,
        )
        entry_widget = entry(settings_frame, width=72)
        entry_widget.insert(0, existing.get(key, ""))
        entry_widget.grid(row=grid_row, column=1, sticky="ew", pady=3)
        entries[key] = entry_widget

    label(
        settings_frame,
        text="Streamlabs / OBS Link",
        anchor="w",
        width=24,
        bg=PANEL_BG,
        fg=MUTED_FG,
    ).grid(row=overlay_link_row, column=0, sticky="w", pady=3)
    overlay_url_var = tk.StringVar(value=DEFAULT_OVERLAY_URL)
    overlay_url_entry = entry(
        settings_frame,
        textvariable=overlay_url_var,
        width=72,
        state="readonly",
        readonlybackground=FIELD_BG,
    )
    overlay_url_entry.grid(row=overlay_link_row, column=1, sticky="ew", pady=3)
    button(
        settings_frame,
        text="Copy Overlay Link",
        command=lambda: (
            copy_to_clipboard(root, DEFAULT_OVERLAY_URL),
            status.set("Copied overlay browser-source link for Streamlabs / OBS."),
        ),
        color="#334b64",
    ).grid(row=overlay_link_row, column=2, padx=(8, 0), sticky="w")

    def choose_graphics_for_field(field_name, title, status_label):
        paths = filedialog.askopenfilenames(
            title=title,
            filetypes=[
                ("Image files", "*.png *.jpg *.jpeg *.webp *.gif *.svg"),
                ("All files", "*.*"),
            ],
        )
        asset_paths = install_overlay_brand_graphics(paths)
        if not asset_paths:
            status.set("No graphics were copied. Choose PNG, JPG, WEBP, GIF, or SVG files.")
            return
        field = entries[field_name]
        field.delete(0, "end")
        field.insert(0, ",".join(asset_paths))
        status.set(f"Added {len(asset_paths)} graphic(s) for {status_label}.")

    def choose_brand_graphics():
        choose_graphics_for_field(
            "OVERLAY_BRAND_GRAPHICS",
            "Choose sponsor / brand logos for the overlay title",
            "the overlay title rotation",
        )

    def choose_practice_music():
        paths = filedialog.askopenfilenames(
            title="Choose practice music files",
            filetypes=[
                ("Audio files", "*.mp3 *.wav *.m4a *.aac *.flac *.wma"),
                ("All files", "*.*"),
            ],
        )
        if not paths:
            return
        field = entries["PRACTICE_MUSIC_PLAYLIST"]
        field.delete(0, "end")
        field.insert(0, format_playlist_paths(paths))
        status.set(f"Added {len(paths)} practice music file(s). Save settings before starting.")

    def choose_single_audio(field_name, title):
        path = filedialog.askopenfilename(
            title=title,
            filetypes=[
                ("Audio files", "*.mp3 *.wav *.m4a *.aac *.flac *.wma"),
                ("All files", "*.*"),
            ],
        )
        if not path:
            return
        updated_values = apply_audio_file_selection(collect_values(), field_name, path)
        for key, value in updated_values.items():
            if key not in entries:
                continue
            field = entries[key]
            field.delete(0, "end")
            field.insert(0, value)
        if field_name == "NATIONAL_ANTHEM_AUDIO":
            status.set("Set RGC Anthem audio and turned USE_NATIONAL_ANTHEM on. Save settings before starting.")
            return
        status.set(f"Set {field_name}. Save settings before starting.")

    button(
        settings_frame,
        text="Choose Sponsor Logos",
        command=choose_brand_graphics,
        color="#334b64",
    ).grid(row=settings_grid_row(overlay_brand_row), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Anthem Audio",
        command=lambda: choose_single_audio("NATIONAL_ANTHEM_AUDIO", "Choose RGC Anthem audio"),
        color="#334b64",
    ).grid(row=settings_grid_row(LAUNCHER_FIELDS.index(("NATIONAL_ANTHEM_AUDIO", ""))), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Anthem Graphics",
        command=lambda: choose_graphics_for_field(
            "NATIONAL_ANTHEM_GRAPHICS",
            "Choose RGC Anthem overlay graphics",
            "the RGC Anthem presentation",
        ),
        color="#334b64",
    ).grid(row=settings_grid_row(LAUNCHER_FIELDS.index(("NATIONAL_ANTHEM_GRAPHICS", ""))), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Practice Music",
        command=choose_practice_music,
        color="#334b64",
    ).grid(row=settings_grid_row(LAUNCHER_FIELDS.index(("PRACTICE_MUSIC_PLAYLIST", ""))), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Caution Audio",
        command=lambda: choose_single_audio("CAUTION_REPLAY_AUDIO", "Choose caution replay audio"),
        color="#334b64",
    ).grid(row=settings_grid_row(LAUNCHER_FIELDS.index(("CAUTION_REPLAY_AUDIO", ""))), column=2, padx=(8, 0), sticky="w")
    button(
        settings_frame,
        text="Choose Caution Graphics",
        command=lambda: choose_graphics_for_field(
            "CAUTION_PRESENTATION_GRAPHICS",
            "Choose caution overlay graphics",
            "the caution presentation",
        ),
        color="#334b64",
    ).grid(row=settings_grid_row(LAUNCHER_FIELDS.index(("CAUTION_PRESENTATION_GRAPHICS", ""))), column=2, padx=(8, 0), sticky="w")

    settings_frame.columnconfigure(1, weight=1)

    label(root, textvariable=status, anchor="w", fg=MUTED_FG).pack(
        fill="x",
        padx=18,
        pady=(8, 0),
    )

    def collect_values():
        values = {key: entry.get().strip() for key, entry in entries.items()}
        values["STUDIO_VOLUME"] = str(int(volume_var.get()))
        return values

    def apply_values_to_form(values):
        values = launcher_defaults(values)
        for key, widget in entries.items():
            widget.delete(0, "end")
            widget.insert(0, values.get(key, ""))
        volume_var.set(int(values.get("STUDIO_VOLUME", "65") or 65))
        update_volume_label(volume_var.get())
        refresh_health()

    def refresh_profile_list():
        profile_combo["values"] = list_profiles()
        status.set("Profile list refreshed.")

    def save_settings():
        save_env_file(collect_values())
        status.set(f"Saved settings to {ENV_PATH}")
        refresh_health()

    def save_current_profile():
        name = profile_name_var.get().strip() or profile_var.get().strip()
        if not name:
            messagebox.showerror("Missing profile name", "Enter a profile name first.")
            return
        path = save_profile(name, collect_values())
        profile_var.set(sanitize_profile_name(name))
        profile_name_var.set("")
        refresh_profile_list()
        status.set(f"Saved profile: {path.name}")

    def load_selected_profile():
        name = profile_var.get().strip()
        if not name:
            messagebox.showerror("Missing profile", "Choose a profile to load first.")
            return
        try:
            values = load_profile(name)
        except Exception as error:
            messagebox.showerror("Profile load failed", str(error))
            return
        apply_values_to_form(values)
        save_env_file(collect_values())
        status.set(f"Loaded profile '{name}' and saved it as the active broadcast settings.")

    def refresh_health():
        for widget in health_rows_frame.winfo_children():
            widget.destroy()
        health_row_widgets.clear()

        rows = build_health_status(
            collect_values(),
            root=ROOT,
            broadcast_running=has_running_broadcast(),
        )
        level_colors = {
            "ok": GREEN,
            "warn": "#d19a2a",
            "off": MUTED_FG,
        }
        ok_count = sum(1 for _name, _state, _detail, level in rows if level == "ok")
        warn_count = sum(1 for _name, _state, _detail, level in rows if level == "warn")
        health_summary.set(f"{ok_count} ready | {warn_count} need attention")

        for index, (name, state_text, detail, level) in enumerate(rows):
            row_frame = frame(health_rows_frame, bg=PANEL_BG)
            row_frame.grid(
                row=index // 2,
                column=index % 2,
                sticky="ew",
                padx=(0, 14),
                pady=3,
            )
            health_rows_frame.columnconfigure(index % 2, weight=1)
            label(
                row_frame,
                text=name,
                width=16,
                anchor="w",
                bg=PANEL_BG,
                fg=MUTED_FG,
                font=("Segoe UI", 9, "bold"),
            ).pack(side="left")
            label(
                row_frame,
                text=state_text,
                width=12,
                anchor="w",
                bg=PANEL_BG,
                fg=level_colors.get(level, MUTED_FG),
                font=("Segoe UI", 9, "bold"),
            ).pack(side="left")
            label(
                row_frame,
                text=detail,
                anchor="w",
                bg=PANEL_BG,
                fg=TEXT_FG,
            ).pack(side="left", fill="x", expand=True)
            health_row_widgets.append(row_frame)
        status.set("Broadcast health refreshed.")

    def create_league_files():
        copied = ensure_league_files()
        if copied:
            messagebox.showinfo("League files created", "\n".join(copied))
        else:
            messagebox.showinfo(
                "League files ready",
                "league/drivers.csv and league/stats.csv already exist.",
            )

    def start_full_ai():
        save_settings()
        process = launch_broadcast(producer_assist=False)
        if process:
            status.set("Started full AI broadcast with overlay, cameras, and incident replay.")
        refresh_health()

    def start_producer_assist():
        save_settings()
        process = launch_broadcast(producer_assist=True)
        if process:
            status.set(
                "Started Producer Assist broadcast with overlay and cameras. "
                "AI voices are disabled so a human broadcaster can call the race."
            )
        refresh_health()

    def stop_running_broadcast():
        stopped_count = stop_broadcast()
        if stopped_count:
            status.set(f"Stopped broadcast process(es): {stopped_count}.")
        else:
            status.set("No running broadcast found from this launcher.")
        refresh_health()

    def on_close():
        if has_running_broadcast():
            should_stop = messagebox.askyesno(
                "Broadcast still running",
                (
                    "A broadcast appears to still be running.\n\n"
                    "Do you want to stop the broadcast before closing RGC AI Broadcast Studio?"
                ),
            )
            if should_stop:
                stop_broadcast()
                root.destroy()
            return
        root.destroy()

    button(action_bar, text="Save Settings", command=save_settings, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Save Profile", command=save_current_profile, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Load Profile", command=load_selected_profile, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Refresh Profiles", command=refresh_profile_list, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Create League Files", command=create_league_files, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Start Broadcast", command=start_full_ai, color=GREEN).pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Start Producer Assist", command=start_producer_assist, color=ACCENT).pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Stop Broadcast", command=stop_running_broadcast, color=STOP_RED).pack(
        side="left",
        padx=6,
        pady=8,
    )
    button(action_bar, text="Refresh Health", command=refresh_health, color="#334b64").pack(
        side="left",
        padx=6,
        pady=8,
    )
    volume_frame = frame(action_bar, bg=PANEL_BG)
    volume_frame.pack(side="left", padx=(14, 6), pady=8)
    label(
        volume_frame,
        text="Studio Volume",
        bg=PANEL_BG,
        fg=MUTED_FG,
        font=("Segoe UI", 9, "bold"),
    ).pack(side="left", padx=(0, 6))
    volume_var = tk.IntVar(value=int(existing.get("STUDIO_VOLUME", existing.get("PRACTICE_MUSIC_VOLUME", "65")) or 65))
    volume_value = tk.StringVar(value=f"{volume_var.get()}%")

    def update_volume_label(value):
        volume_value.set(f"{int(float(value))}%")

    tk.Scale(
        volume_frame,
        from_=0,
        to=100,
        orient="horizontal",
        variable=volume_var,
        command=update_volume_label,
        length=150,
        bg=PANEL_BG,
        fg=TEXT_FG,
        troughcolor=FIELD_BG,
        highlightthickness=0,
        activebackground=ACCENT,
    ).pack(side="left")
    label(
        volume_frame,
        textvariable=volume_value,
        bg=PANEL_BG,
        fg=TEXT_FG,
        width=4,
    ).pack(side="left", padx=(4, 0))

    build_league_tab(league_content, status, label, frame, entry, button)
    refresh_health()
    root.protocol("WM_DELETE_WINDOW", on_close)

    root.mainloop()


def build_league_tab(parent, status, label, frame, entry, button):
    import tkinter as tk

    intro = (
        "Import league stats from Sim Racer Hub. You can use the clean URL "
        "https://simracerhub.com with League, Series, and Season IDs. "
        "Track history is optional and only helps pre-load driver stats for an upcoming track."
    )
    label(parent, text=intro, anchor="w", justify="left", wraplength=900, bg=PANEL_BG, fg=MUTED_FG).pack(
        fill="x",
        padx=14,
        pady=(10, 8),
    )

    form = frame(parent, bg=PANEL_BG)
    form.pack(fill="x", padx=14)

    defaults = {
        "source": "https://simracerhub.com",
        "league_id": "",
        "series_id": "",
        "season_id": "",
        "track_name": "",
        "min_starts": "2",
        "output": "league/stats.csv",
        "drivers_output": "league/drivers.csv",
    }
    entries = {}
    rows = [
        ("Sim Racer Hub URL", "source"),
        ("League ID", "league_id"),
        ("Series ID", "series_id"),
        ("Season ID", "season_id"),
        ("Track History Filter", "track_name"),
        ("Minimum Starts", "min_starts"),
        ("Stats Output CSV", "output"),
        ("Drivers Output CSV", "drivers_output"),
    ]
    for row_number, (label_text, key) in enumerate(rows):
        label(form, text=label_text, anchor="w", width=22, bg=PANEL_BG, fg=MUTED_FG).grid(
            row=row_number,
            column=0,
            sticky="w",
            pady=4,
        )
        entry_widget = entry(form, width=86)
        entry_widget.insert(0, defaults[key])
        entry_widget.grid(row=row_number, column=1, sticky="ew", pady=4)
        entries[key] = entry_widget
    form.columnconfigure(1, weight=1)

    career_mode = tk.BooleanVar(value=False)
    tk.Checkbutton(
        form,
        text="Career Mode: import all seasons in this series instead of one season",
        variable=career_mode,
        bg=PANEL_BG,
        fg=TEXT_FG,
        activebackground=PANEL_BG,
        activeforeground=TEXT_FG,
        selectcolor=FIELD_BG,
    ).grid(row=len(rows), column=1, sticky="w", pady=(4, 8))

    output_box = tk.Text(
        parent,
        height=18,
        wrap="none",
        bg="#08111a",
        fg=TEXT_FG,
        insertbackground=TEXT_FG,
        relief="flat",
        highlightthickness=1,
        highlightbackground="#26384c",
    )
    output_box.pack(fill="both", expand=True, padx=14, pady=(8, 0))

    def values():
        return {key: entry.get().strip() for key, entry in entries.items()}

    def set_output(text):
        output_box.delete("1.0", "end")
        output_box.insert("1.0", text)

    def run_import(dry_run, drivers_only=False):
        data = values()
        if not data["source"]:
            messagebox.showerror("Missing URL", "Paste a Sim Racer Hub URL first.")
            return

        result = run_sim_racer_hub_import(
            source=data["source"],
            league_id=data["league_id"],
            series_id=data["series_id"],
            season_id=data["season_id"],
            track_name=data["track_name"],
            min_starts=data["min_starts"],
            output=data["output"],
            drivers_output=data["drivers_output"],
            career_mode=career_mode.get(),
            dry_run=dry_run,
            drivers_only=drivers_only,
        )
        combined_output = result.stdout
        if result.stderr:
            combined_output += "\n" + result.stderr
        set_output(combined_output or "(No output)")
        if result.returncode == 0:
            action = "Previewed" if dry_run else "Imported"
            mode = "career" if career_mode.get() else "season"
            if drivers_only:
                target = data["drivers_output"] or "league/drivers.csv"
            else:
                target = data["output"] or "league/stats.csv"
            data_type = "driver roster" if drivers_only else "stats"
            suffix = "" if dry_run else f" to {target}"
            status.set(f"{action} Sim Racer Hub {mode} {data_type}{suffix}.")
        else:
            status.set("Sim Racer Hub import failed. Check the output panel.")

    buttons = frame(parent, bg=PANEL_BG)
    buttons.pack(fill="x", padx=14, pady=10)
    button(buttons, text="Preview Stats", command=lambda: run_import(True), color="#334b64").pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Import Stats", command=lambda: run_import(False), color=GREEN).pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Preview Driver Roster", command=lambda: run_import(True, True), color="#334b64").pack(
        side="left",
        padx=4,
    )
    button(buttons, text="Import Driver Roster", command=lambda: run_import(False, True), color=GREEN).pack(
        side="left",
        padx=4,
    )
    label(
        buttons,
        text="Tip: leave Track History blank for general stats; use Career Mode for all seasons.",
        anchor="w",
        bg=PANEL_BG,
        fg=MUTED_FG,
    ).pack(side="left", padx=12)


def main():
    run_gui()


if __name__ == "__main__":
    main()
