import json
import urllib.error
import urllib.request

from config import (
    DISCORD_RACE_REPORT_ENABLED,
    DISCORD_RACE_REPORT_CHAMPIONSHIP_URL,
    DISCORD_RACE_REPORT_RESULTS_URL,
    DISCORD_RACE_REPORT_USE_OPENAI,
    DISCORD_RACE_REPORT_WEBHOOK_URL,
    OVERLAY_EVENT_TITLE,
    OVERLAY_SERIES_NAME,
)


class DiscordRaceReporter:
    """Posts a post-race summary to a Discord channel webhook."""

    def __init__(
        self,
        enabled=DISCORD_RACE_REPORT_ENABLED,
        webhook_url=DISCORD_RACE_REPORT_WEBHOOK_URL,
        use_openai=DISCORD_RACE_REPORT_USE_OPENAI,
        results_url=DISCORD_RACE_REPORT_RESULTS_URL,
        championship_url=DISCORD_RACE_REPORT_CHAMPIONSHIP_URL,
        event_title=OVERLAY_EVENT_TITLE,
        series_name=OVERLAY_SERIES_NAME,
        opener=None,
    ):
        self.enabled = bool(enabled)
        self.webhook_url = str(webhook_url or "").strip()
        self.use_openai = bool(use_openai)
        self.results_url = str(results_url or "").strip()
        self.championship_url = str(championship_url or "").strip()
        self.event_title = str(event_title or "RGC AI Broadcast").strip()
        self.series_name = str(series_name or "").strip()
        self.opener = opener or urllib.request.urlopen
        self.posted = False
        self.last_error = ""

    def reset(self):
        self.posted = False
        self.last_error = ""

    def ready(self):
        return self.enabled and bool(self.webhook_url)

    def post_once(
        self,
        results,
        driver_lookup,
        track_info=None,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        if self.posted:
            return False, "Discord race report already posted."
        if not self.ready():
            return False, "Discord race report is disabled or missing a webhook URL."

        payload = self.build_payload(
            results=results,
            driver_lookup=driver_lookup,
            track_info=track_info,
            total_laps=total_laps,
            race_state=race_state,
            openai_director=openai_director,
        )
        ok, message = self.send_payload(payload)
        if ok:
            self.posted = True
        else:
            self.last_error = message
        return ok, message

    def build_payload(
        self,
        results,
        driver_lookup,
        track_info=None,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        ordered = self.sort_results(results or [])
        track_name = self.track_name(track_info)
        title_parts = [part for part in [self.series_name, self.event_title] if part]
        title = " - ".join(title_parts) if title_parts else "Race Report"
        if track_name:
            title = f"{title} at {track_name}"

        breakdown = self.ai_breakdown(
            ordered,
            driver_lookup,
            track_name,
            total_laps=total_laps,
            race_state=race_state,
            openai_director=openai_director,
        )
        top_ten = self.format_top_finishers(ordered, driver_lookup, limit=10)
        movers = self.format_biggest_movers(ordered, driver_lookup, limit=5)
        stats = self.format_race_stats(ordered, driver_lookup, total_laps, race_state)

        fields = [
            {"name": "Top 10", "value": top_ten or "Finishing order was not available.", "inline": False},
        ]
        if movers:
            fields.append({"name": "Biggest Movers", "value": movers, "inline": False})
        if stats:
            fields.append({"name": "Race Stats", "value": stats, "inline": False})
        links = self.format_result_links()
        if links:
            fields.append({"name": "Official Links", "value": links, "inline": False})

        winner = self.driver_label(ordered[0], driver_lookup) if ordered else "the race winner"
        return {
            "username": "RGC AI Broadcast Studio",
            "content": f"Race report posted for {winner}.",
            "embeds": [
                {
                    "title": title,
                    "description": breakdown,
                    "color": 9117229,
                    "fields": fields,
                    "footer": {"text": "Generated by RGC AI Broadcast Studio"},
                }
            ],
        }

    def format_result_links(self):
        links = []
        if self.results_url:
            links.append(f"[Race results]({self.results_url})")
        if self.championship_url:
            links.append(f"[Championship standings]({self.championship_url})")
        return "\n".join(links)

    def ai_breakdown(
        self,
        ordered,
        driver_lookup,
        track_name,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        fallback = self.fallback_breakdown(ordered, driver_lookup, track_name, total_laps, race_state)
        if not self.use_openai or not openai_director or not openai_director.is_enabled():
            return fallback

        try:
            prompt = self.openai_prompt(ordered, driver_lookup, track_name, total_laps, race_state)
            response = openai_director.client.responses.create(
                model=openai_director.model,
                input=[
                    {
                        "role": "system",
                        "content": (
                            "You write concise post-race Discord recaps for an iRacing league. "
                            "Sound like a professional short-form motorsports report. "
                            "Do not invent facts not in the data."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                max_output_tokens=300,
            )
            text = response.output_text.strip()
            return text[:3900] if text else fallback
        except Exception:
            return fallback

    def fallback_breakdown(self, ordered, driver_lookup, track_name, total_laps=0, race_state=None):
        if not ordered:
            return "The race is complete. Finishing data was not available for the automatic recap."
        winner = self.driver_label(ordered[0], driver_lookup)
        podium = [self.driver_label(car, driver_lookup) for car in ordered[:3]]
        lap_text = f" after {total_laps} laps" if self.safe_int(total_laps) > 0 else ""
        track_text = f" at {track_name}" if track_name else ""
        parts = [
            f"{winner} takes the win{track_text}{lap_text}.",
        ]
        if len(podium) >= 3:
            parts.append(f"The podium finished with {podium[0]}, {podium[1]}, and {podium[2]}.")
        movers = self.biggest_movers(ordered, driver_lookup, limit=1)
        if movers:
            mover = movers[0]
            direction = "gained" if mover["delta"] > 0 else "lost"
            parts.append(
                f"One of the biggest stories was {mover['label']}, who {direction} "
                f"{abs(mover['delta'])} spots from the start."
            )
        return " ".join(parts)

    def openai_prompt(self, ordered, driver_lookup, track_name, total_laps=0, race_state=None):
        lines = [
            f"Track: {track_name or 'Unknown'}",
            f"Total laps: {total_laps or 'Unknown'}",
            "Finishing order:",
        ]
        for car in ordered[:15]:
            lines.append(self.result_line(car, driver_lookup))
        movers = self.format_biggest_movers(ordered, driver_lookup, limit=5)
        if movers:
            lines.append("Biggest movers:")
            lines.append(movers)
        stats = self.format_race_stats(ordered, driver_lookup, total_laps, race_state)
        if stats:
            lines.append("Race stats:")
            lines.append(stats)
        lines.append("Write 2 short paragraphs for Discord, then one short sentence about the top story.")
        return "\n".join(lines)

    def send_payload(self, payload):
        body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self.webhook_url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "User-Agent": "RGC-AI-Broadcast-Studio",
            },
            method="POST",
        )
        try:
            with self.opener(request, timeout=10) as response:
                status = getattr(response, "status", 204)
                if 200 <= int(status) < 300:
                    return True, "Discord race report posted."
                return False, f"Discord webhook returned HTTP {status}."
        except urllib.error.HTTPError as error:
            return False, f"Discord webhook returned HTTP {error.code}."
        except Exception as error:
            return False, f"Discord race report failed: {error}"

    def format_top_finishers(self, ordered, driver_lookup, limit=10):
        return "\n".join(self.result_line(car, driver_lookup) for car in ordered[:limit])

    def result_line(self, car, driver_lookup):
        position = self.display_position(car)
        return f"{self.ordinal(position)} - {self.driver_label(car, driver_lookup)}"

    def format_biggest_movers(self, ordered, driver_lookup, limit=5):
        movers = self.biggest_movers(ordered, driver_lookup, limit=limit)
        return "\n".join(
            f"{mover['label']}: {mover['delta']:+d} spots"
            for mover in movers
        )

    def biggest_movers(self, ordered, driver_lookup, limit=5):
        movers = []
        for car in ordered:
            start = self.starting_position(car)
            finish = self.display_position(car)
            if start <= 0 or finish <= 0:
                continue
            delta = start - finish
            if delta == 0:
                continue
            movers.append(
                {
                    "delta": delta,
                    "label": self.driver_label(car, driver_lookup),
                }
            )
        movers.sort(key=lambda item: abs(item["delta"]), reverse=True)
        return movers[:limit]

    def format_race_stats(self, ordered, driver_lookup, total_laps, race_state):
        stats = []
        if self.safe_int(total_laps) > 0:
            stats.append(f"Scheduled distance: {self.safe_int(total_laps)} laps")
        green_laps = self.safe_int(getattr(race_state, "green_laps", 0))
        caution_laps = self.safe_int(getattr(race_state, "caution_laps", 0))
        caution_count = self.safe_int(getattr(race_state, "cautions", 0) or getattr(race_state, "caution_count", 0))
        if green_laps > 0:
            stats.append(f"Green-flag laps: {green_laps}")
        if caution_laps > 0:
            stats.append(f"Caution laps tracked: {caution_laps}")
        if caution_count > 0:
            stats.append(f"Cautions tracked: {caution_count}")

        led = []
        for car in ordered:
            laps_led = self.safe_int(car.get("LapsLed", car.get("laps_led", 0)))
            if laps_led > 0:
                led.append((laps_led, self.driver_label(car, driver_lookup)))
        led.sort(reverse=True)
        if led:
            stats.append(f"Most laps led in results: {led[0][1]} ({led[0][0]})")
        return "\n".join(stats)

    def driver_label(self, car, driver_lookup):
        car_idx = car.get("CarIdx")
        driver = driver_lookup.get(car_idx, {}) if isinstance(driver_lookup, dict) else {}
        number = driver.get("number") or car.get("CarNumber") or car.get("CarNumberRaw") or "?"
        name = driver.get("name") or car.get("UserName") or f"Car {car_idx}"
        return f"#{number} {name}"

    def sort_results(self, results):
        return sorted(results or [], key=lambda car: self.display_position(car))

    def display_position(self, car):
        raw = self.safe_int(car.get("Position"), 999)
        if raw <= 0:
            return raw + 1
        return raw

    def starting_position(self, car):
        for key in ("StartingPosition", "StartPosition", "QualifyPosition", "ClassStartingPosition"):
            value = self.safe_int(car.get(key), 0)
            if value > 0:
                return value
        return 0

    def track_name(self, track_info):
        if not isinstance(track_info, dict):
            return ""
        return (
            track_info.get("track_name")
            or track_info.get("TrackDisplayName")
            or track_info.get("TrackName")
            or ""
        )

    @staticmethod
    def ordinal(value):
        value = DiscordRaceReporter.safe_int(value)
        if value <= 0:
            return "--"
        if 10 <= value % 100 <= 20:
            suffix = "th"
        else:
            suffix = {1: "st", 2: "nd", 3: "rd"}.get(value % 10, "th")
        return f"{value}{suffix}"

    @staticmethod
    def safe_int(value, default=0):
        try:
            return int(value)
        except (TypeError, ValueError):
            return default
