import csv
import json
import re
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime
from pathlib import Path

from config import (
    DISCORD_RACE_REPORT_ENABLED,
    DISCORD_RACE_REPORT_USE_OPENAI,
    DISCORD_RACE_REPORT_WEBHOOK_URL,
    OVERLAY_EVENT_TITLE,
    OVERLAY_SERIES_NAME,
    SIMRACERHUB_RACE_SCHEDULE_CSV,
    SIMRACERHUB_SEASON_ID,
    SIMRACERHUB_SOURCE,
)


class DiscordRaceReporter:
    """Posts a post-race summary to a Discord channel webhook."""

    def __init__(
        self,
        enabled=DISCORD_RACE_REPORT_ENABLED,
        webhook_url=DISCORD_RACE_REPORT_WEBHOOK_URL,
        use_openai=DISCORD_RACE_REPORT_USE_OPENAI,
        sim_racer_hub_source=SIMRACERHUB_SOURCE,
        sim_racer_hub_season_id=SIMRACERHUB_SEASON_ID,
        race_schedule_csv=SIMRACERHUB_RACE_SCHEDULE_CSV,
        event_title=OVERLAY_EVENT_TITLE,
        series_name=OVERLAY_SERIES_NAME,
        opener=None,
        current_date=None,
    ):
        self.enabled = bool(enabled)
        self.webhook_url = str(webhook_url or "").strip()
        self.use_openai = bool(use_openai)
        self.sim_racer_hub_source = str(sim_racer_hub_source or "https://simracerhub.com").strip()
        self.sim_racer_hub_season_id = str(sim_racer_hub_season_id or "").strip()
        self.race_schedule_csv = str(race_schedule_csv or "").strip()
        self.event_title = str(event_title or "RGC AI Broadcast").strip()
        self.series_name = str(series_name or "").strip()
        self.opener = opener or urllib.request.urlopen
        self.current_date = current_date
        self.posted = False
        self.last_error = ""

    def reset(self):
        self.posted = False
        self.last_error = ""

    def ready(self):
        return self.enabled and bool(self.webhook_url)

    def post_once(
        self,
        results,
        driver_lookup,
        track_info=None,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        if self.posted:
            return False, "Discord race report already posted."
        if not self.ready():
            return False, "Discord race report is disabled or missing a webhook URL."

        payload = self.build_payload(
            results=results,
            driver_lookup=driver_lookup,
            track_info=track_info,
            total_laps=total_laps,
            race_state=race_state,
            openai_director=openai_director,
        )
        ok, message = self.send_payload(payload)
        if ok:
            self.posted = True
        else:
            self.last_error = message
        return ok, message

    def build_payload(
        self,
        results,
        driver_lookup,
        track_info=None,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        ordered = self.sort_results(results or [])
        track_name = self.track_name(track_info)
        title_parts = [part for part in [self.series_name, self.event_title] if part]
        title = " - ".join(title_parts) if title_parts else "Race Report"
        if track_name:
            title = f"{title} at {track_name}"

        breakdown = self.ai_breakdown(
            ordered,
            driver_lookup,
            track_name,
            total_laps=total_laps,
            race_state=race_state,
            openai_director=openai_director,
        )
        top_ten = self.format_top_finishers(ordered, driver_lookup, limit=10)
        movers = self.format_biggest_movers(ordered, driver_lookup, limit=5)
        stats = self.format_race_stats(ordered, driver_lookup, total_laps, race_state)

        fields = [
            {"name": "Top 10", "value": top_ten or "Finishing order was not available.", "inline": False},
        ]
        if movers:
            fields.append({"name": "Biggest Movers", "value": movers, "inline": False})
        if stats:
            fields.append({"name": "Race Stats", "value": stats, "inline": False})
        links = self.format_result_links(track_name)
        if links:
            fields.append({"name": "Official Links", "value": links, "inline": False})

        winner = self.driver_label(ordered[0], driver_lookup) if ordered else "the race winner"
        return {
            "username": "RGC AI Broadcast Studio",
            "content": f"Race report posted for {winner}.",
            "embeds": [
                {
                    "title": title,
                    "description": breakdown,
                    "color": 9117229,
                    "fields": fields,
                    "footer": {"text": "Generated by RGC AI Broadcast Studio"},
                }
            ],
        }

    def format_result_links(self, track_name=""):
        links = []
        schedule_match = self.scheduled_race_for_track(track_name)
        results_url = self.resolve_scheduled_results_url(track_name, schedule_match=schedule_match)
        if results_url:
            links.append(f"[Race results]({results_url})")
        championship_url = self.resolve_scheduled_championship_url(schedule_match)
        if championship_url:
            links.append(f"[Championship standings]({championship_url})")
        return "\n".join(links)

    def resolve_scheduled_results_url(self, track_name="", schedule_match=None):
        match = schedule_match or self.scheduled_race_for_track(track_name)
        if not match:
            return ""
        schedule_id = match.get("schedule_id") or match.get("race_id")
        if not schedule_id:
            return ""
        return self.sim_racer_hub_race_url(schedule_id)

    def resolve_scheduled_championship_url(self, schedule_match=None):
        series_id = self.sim_racer_hub_query_value("series_id")
        if series_id:
            return self.sim_racer_hub_series_standings_url(series_id)

        season_id = self.sim_racer_hub_season_id or self.sim_racer_hub_query_value("season_id")
        if not season_id:
            return ""
        schedule_id = ""
        if schedule_match:
            schedule_id = schedule_match.get("schedule_id") or schedule_match.get("race_id") or ""
        schedule_id = schedule_id or self.sim_racer_hub_query_value("schedule_id")
        if not schedule_id:
            return ""
        return self.sim_racer_hub_standings_url(season_id, schedule_id)

    def scheduled_race_for_track(self, track_name=""):
        path = self.resolve_schedule_path(self.race_schedule_csv)
        if not path or not path.exists():
            return {}
        wanted = self.normalize_track_name(track_name)
        if not wanted:
            return {}
        matches = []
        try:
            with path.open("r", encoding="utf-8-sig", newline="") as handle:
                for row in csv.DictReader(handle):
                    row_track = (
                        row.get("track_name")
                        or row.get("track")
                        or row.get("track_display_name")
                        or ""
                    )
                    if self.tracks_match(wanted, row_track):
                        matches.append({
                            "track_name": row_track,
                            "schedule_id": str(row.get("schedule_id") or "").strip(),
                            "race_id": str(row.get("race_id") or "").strip(),
                            "notes": str(row.get("notes") or "").strip(),
                            "race_date": str(row.get("race_date") or "").strip(),
                        })
        except Exception:
            return {}
        return self.choose_schedule_match(matches)

    def choose_schedule_match(self, matches):
        if not matches:
            return {}
        if len(matches) == 1:
            return matches[0]

        today = self.today()
        dated = []
        for index, match in enumerate(matches):
            race_date = self.parse_schedule_date(
                match.get("race_date") or match.get("notes") or ""
            )
            if race_date:
                dated.append((abs((race_date - today).days), index, match))

        if dated:
            return sorted(dated, key=lambda item: (item[0], item[1]))[0][2]

        return matches[0]

    def today(self):
        if isinstance(self.current_date, date):
            return self.current_date
        parsed = self.parse_schedule_date(self.current_date)
        return parsed or date.today()

    @classmethod
    def parse_schedule_date(cls, value):
        text = str(value or "").strip()
        if not text:
            return None

        iso_match = re.search(r"\d{4}-\d{2}-\d{2}", text)
        if iso_match:
            try:
                return date.fromisoformat(iso_match.group(0))
            except ValueError:
                pass

        for pattern in (
            "%b %d, %Y",
            "%B %d, %Y",
            "%b %d %Y",
            "%B %d %Y",
            "%m/%d/%Y",
            "%m-%d-%Y",
        ):
            try:
                return datetime.strptime(text, pattern).date()
            except ValueError:
                continue

        month_match = re.search(
            r"\b("
            r"jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|"
            r"jul(?:y)?|aug(?:ust)?|sep(?:tember)?|oct(?:ober)?|"
            r"nov(?:ember)?|dec(?:ember)?"
            r")\.?\s+\d{1,2},?\s+\d{4}\b",
            text,
            flags=re.IGNORECASE,
        )
        if month_match:
            return cls.parse_schedule_date(month_match.group(0).replace(".", ""))

        return None

    def sim_racer_hub_race_url(self, schedule_id):
        base = self.sim_racer_hub_base_url()
        return f"{base}/scoring/season_race.php?schedule_id={schedule_id}"

    def sim_racer_hub_standings_url(self, season_id, schedule_id):
        base = self.sim_racer_hub_base_url()
        return f"{base}/season_standings.php?season_id={season_id}&schedule_id={schedule_id}"

    def sim_racer_hub_series_standings_url(self, series_id):
        base = self.sim_racer_hub_base_url()
        return f"{base}/scoring/season_standings.php?series_id={series_id}"

    def sim_racer_hub_base_url(self):
        parsed = urllib.parse.urlparse(self.sim_racer_hub_source or "https://simracerhub.com")
        scheme = parsed.scheme or "https"
        netloc = parsed.netloc or "simracerhub.com"
        return f"{scheme}://{netloc}".rstrip("/")

    def sim_racer_hub_query_value(self, key):
        parsed = urllib.parse.urlparse(self.sim_racer_hub_source or "")
        return urllib.parse.parse_qs(parsed.query).get(key, [""])[0]

    @staticmethod
    def resolve_schedule_path(path):
        text = str(path or "").strip()
        if not text:
            return None
        candidate = Path(text)
        if candidate.is_absolute():
            return candidate
        return Path.cwd() / candidate

    @classmethod
    def tracks_match(cls, wanted_normalized, row_track):
        candidate = cls.normalize_track_name(row_track)
        if not wanted_normalized or not candidate:
            return False
        return wanted_normalized == candidate or wanted_normalized in candidate or candidate in wanted_normalized

    @staticmethod
    def normalize_track_name(track_name):
        text = str(track_name or "").lower()
        text = text.replace("&", " and ")
        text = re.sub(
            r"\b(international speedway|motor speedway|motorsports park|"
            r"superspeedway|speedway|raceway|oval|road course)\b",
            " ",
            text,
        )
        text = re.sub(r"[^a-z0-9]+", " ", text)
        return " ".join(text.split())

    def ai_breakdown(
        self,
        ordered,
        driver_lookup,
        track_name,
        total_laps=0,
        race_state=None,
        openai_director=None,
    ):
        fallback = self.fallback_breakdown(ordered, driver_lookup, track_name, total_laps, race_state)
        if not self.use_openai or not openai_director or not openai_director.is_enabled():
            return fallback

        try:
            prompt = self.openai_prompt(ordered, driver_lookup, track_name, total_laps, race_state)
            response = openai_director.client.responses.create(
                model=openai_director.model,
                input=[
                    {
                        "role": "system",
                        "content": (
                            "You write concise post-race Discord recaps for an iRacing league. "
                            "Sound like a professional short-form motorsports report. "
                            "Do not invent facts not in the data."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                max_output_tokens=300,
            )
            text = response.output_text.strip()
            return text[:3900] if text else fallback
        except Exception:
            return fallback

    def fallback_breakdown(self, ordered, driver_lookup, track_name, total_laps=0, race_state=None):
        if not ordered:
            return "The race is complete. Finishing data was not available for the automatic recap."
        winner = self.driver_label(ordered[0], driver_lookup)
        podium = [self.driver_label(car, driver_lookup) for car in ordered[:3]]
        lap_text = f" after {total_laps} laps" if self.safe_int(total_laps) > 0 else ""
        track_text = f" at {track_name}" if track_name else ""
        parts = [
            f"{winner} takes the win{track_text}{lap_text}.",
        ]
        if len(podium) >= 3:
            parts.append(f"The podium finished with {podium[0]}, {podium[1]}, and {podium[2]}.")
        movers = self.biggest_movers(ordered, driver_lookup, limit=1)
        if movers:
            mover = movers[0]
            direction = "gained" if mover["delta"] > 0 else "lost"
            parts.append(
                f"One of the biggest stories was {mover['label']}, who {direction} "
                f"{abs(mover['delta'])} spots from the start."
            )
        return " ".join(parts)

    def openai_prompt(self, ordered, driver_lookup, track_name, total_laps=0, race_state=None):
        lines = [
            f"Track: {track_name or 'Unknown'}",
            f"Total laps: {total_laps or 'Unknown'}",
            "Finishing order:",
        ]
        for car in ordered[:15]:
            lines.append(self.result_line(car, driver_lookup))
        movers = self.format_biggest_movers(ordered, driver_lookup, limit=5)
        if movers:
            lines.append("Biggest movers:")
            lines.append(movers)
        stats = self.format_race_stats(ordered, driver_lookup, total_laps, race_state)
        if stats:
            lines.append("Race stats:")
            lines.append(stats)
        lines.append("Write 2 short paragraphs for Discord, then one short sentence about the top story.")
        return "\n".join(lines)

    def send_payload(self, payload):
        body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self.webhook_url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "User-Agent": "RGC-AI-Broadcast-Studio",
            },
            method="POST",
        )
        try:
            with self.opener(request, timeout=10) as response:
                status = getattr(response, "status", 204)
                if 200 <= int(status) < 300:
                    return True, "Discord race report posted."
                return False, f"Discord webhook returned HTTP {status}."
        except urllib.error.HTTPError as error:
            return False, f"Discord webhook returned HTTP {error.code}."
        except Exception as error:
            return False, f"Discord race report failed: {error}"

    def format_top_finishers(self, ordered, driver_lookup, limit=10):
        return "\n".join(self.result_line(car, driver_lookup) for car in ordered[:limit])

    def result_line(self, car, driver_lookup):
        position = self.display_position(car)
        return f"{self.ordinal(position)} - {self.driver_label(car, driver_lookup)}"

    def format_biggest_movers(self, ordered, driver_lookup, limit=5):
        movers = self.biggest_movers(ordered, driver_lookup, limit=limit)
        return "\n".join(
            f"{mover['label']}: {mover['delta']:+d} spots"
            for mover in movers
        )

    def biggest_movers(self, ordered, driver_lookup, limit=5):
        movers = []
        for car in ordered:
            start = self.starting_position(car)
            finish = self.display_position(car)
            if start <= 0 or finish <= 0:
                continue
            delta = start - finish
            if delta == 0:
                continue
            movers.append(
                {
                    "delta": delta,
                    "label": self.driver_label(car, driver_lookup),
                }
            )
        movers.sort(key=lambda item: abs(item["delta"]), reverse=True)
        return movers[:limit]

    def format_race_stats(self, ordered, driver_lookup, total_laps, race_state):
        stats = []
        if self.safe_int(total_laps) > 0:
            stats.append(f"Scheduled distance: {self.safe_int(total_laps)} laps")
        green_laps = self.safe_int(getattr(race_state, "green_laps", 0))
        caution_laps = self.safe_int(getattr(race_state, "caution_laps", 0))
        caution_count = self.safe_int(getattr(race_state, "cautions", 0) or getattr(race_state, "caution_count", 0))
        if green_laps > 0:
            stats.append(f"Green-flag laps: {green_laps}")
        if caution_laps > 0:
            stats.append(f"Caution laps tracked: {caution_laps}")
        if caution_count > 0:
            stats.append(f"Cautions tracked: {caution_count}")

        led = []
        for car in ordered:
            laps_led = self.safe_int(car.get("LapsLed", car.get("laps_led", 0)))
            if laps_led > 0:
                led.append((laps_led, self.driver_label(car, driver_lookup)))
        led.sort(reverse=True)
        if led:
            stats.append(f"Most laps led in results: {led[0][1]} ({led[0][0]})")
        return "\n".join(stats)

    def driver_label(self, car, driver_lookup):
        car_idx = car.get("CarIdx")
        driver = driver_lookup.get(car_idx, {}) if isinstance(driver_lookup, dict) else {}
        number = driver.get("number") or car.get("CarNumber") or car.get("CarNumberRaw") or "?"
        name = driver.get("name") or car.get("UserName") or f"Car {car_idx}"
        return f"#{number} {name}"

    def sort_results(self, results):
        return sorted(results or [], key=lambda car: self.display_position(car))

    def display_position(self, car):
        raw = self.safe_int(car.get("Position"), 999)
        if raw <= 0:
            return raw + 1
        return raw

    def starting_position(self, car):
        for key in ("StartingPosition", "StartPosition", "QualifyPosition", "ClassStartingPosition"):
            value = self.safe_int(car.get(key), 0)
            if value > 0:
                return value
        return 0

    def track_name(self, track_info):
        if not isinstance(track_info, dict):
            return ""
        return (
            track_info.get("track_name")
            or track_info.get("TrackDisplayName")
            or track_info.get("TrackName")
            or ""
        )

    @staticmethod
    def ordinal(value):
        value = DiscordRaceReporter.safe_int(value)
        if value <= 0:
            return "--"
        if 10 <= value % 100 <= 20:
            suffix = "th"
        else:
            suffix = {1: "st", 2: "nd", 3: "rd"}.get(value % 10, "th")
        return f"{value}{suffix}"

    @staticmethod
    def safe_int(value, default=0):
        try:
            return int(value)
        except (TypeError, ValueError):
            return default
